# Generated by Django 4.0.4 on 2022-04-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0003_nab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NB',
        ),
    ]
